// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDojr2woKXo10sHLxR9KeMq_0_1o8chr1c',
    appId: '1:179207781659:android:88997f789649cabbd6e7be',
    messagingSenderId: '179207781659',
    projectId: 'messageme-app-21815',
    storageBucket: 'messageme-app-21815.firebasestorage.app',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClk7ks8Af4KoJ7_NOGWPL3UbiNk-Al308',
    appId: '1:179207781659:ios:a2f9e953b8f1f6ebd6e7be',
    messagingSenderId: '179207781659',
    projectId: 'messageme-app-21815',
    storageBucket: 'messageme-app-21815.firebasestorage.app',
    iosBundleId: 'com.example.messagemeApp',
  );

  static FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClk7ks8Af4KoJ7_NOGWPL3UbiNk-Al308',
    appId: '1:179207781659:ios:a2f9e953b8f1f6ebd6e7be',
    messagingSenderId: '179207781659',
    projectId: 'messageme-app-21815',
    storageBucket: 'messageme-app-21815.firebasestorage.app',
    iosBundleId: 'com.example.messagemeApp',
  );
}
